[package]
name = "user_management"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
jsonwebtoken = "9.3.0"
rusqlite = { version = "0.32.0", features = ["bundled"] }
serde = "1.0.204"
serde_json = "1.0.121"